### PR TITLE
Use api instead of raw queries

### PR DESCRIPTION
**Pull request by colemanw**
- Avoids sql injection
- Properly filters statuses by case type (pending https://github.com/civicrm/civicrm-core/pull/10552 )
- Logs Change Case Status activity

### CODE REVIEW

**Review by mr-vara — COMMENTED** [review]
Thank you vary much "colemanw". I am new to CiviCRM Development. I am getting some errors while executing this in my development environment. With the information you have given, I'll go on my own to nourish my skills.

**Comment by colemanw** [comment]
You're welcome. I did that PR without any testing (just quickly wrote 
that code in github without checking out your extension) so if it has 
any minor typos or errors, my apologies. But in general that approach 
should work well.

**Comment by mr-vara** [comment]
I like the approach you suggested. But I actually don't know how to do this in CiviCRM Environment. Now I understood by your PR. There are two minor typos and I have corrected them. But the problem is...
This line "$this->set('caseid') = (int) $_GET['caseid'];" causing following error:
image .

**Comment by colemanw** [comment]
Whoops. Big typo. It should have been

    $this->set('caseid', (int) $_GET['caseid']);

**Comment by mr-vara** [comment]
Done. Thank you

**Comment by colemanw** [comment]
@mr-vara I don't see any commits & this PR is still open.
Hint: did you know you can make changes by pushing directly to this pr?

**Review by mr-vara — APPROVED** [review]

**Pull request merged**
